# Q1: Fun with arrays

In [27]:
import numpy as np

#Part A
v = (np.arange(1, 16).reshape(3, 5)).transpose()
print(v)

v_p = v[1:4:2]
print(v_p)


#Part B
lines = 4
columns = 5
v2 = np.zeros((lines, columns), dtype=int)
v2[0,:] = 1
v2[lines-1, :] = 1
v2[:, 0] = 1
v2[:, columns-1] = 1
print(v2)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 2  7 12]
 [ 4  9 14]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Q2: Histograms

In [1]:
import numpy as np

x = np.loadtxt('sample.txt', unpack=True)

hist1, nbin = np.histogram(x, 10)

m=np.zeros(len(nbin))    

m = (nbin[1:] + nbin[:-1])/2

print('bin center  counts')
for i, j in zip(m[1:len(m)], hist1):
    print(i, j)

bin center  counts
-20.21093194037355 3
-13.29260130874136 4
-6.374270677109173 9
0.5440599545230143 22
7.462390586155202 22
14.38072121778739 22
21.299051849419577 9
28.217382481051764 7
35.135713112683945 1


# Q3: Are you faster than numpy? No

In [22]:
import numpy as np
import time

a = np.arange(1000)

def a_std(a):
    a_mean = sum(a)/len(a)
    num = (a[0:]-a_mean)**2
    s = np.sqrt(sum(num)/len(a))
    return s

t0 = time.time()
for i in range(1000):
    my_std = a_std(a)
    
t1 = time.time()

print('my result:', a_std(a))
print("runtime: {} s".format((t1-t0)/1000))

t2 = time.time()
for i in range(1000):
    st = np.std(a) 

t3 = time.time()
print('numpy function:', np.std(a))
print("runtime: {} s".format((t3-t2)/1000))

my result: 288.6749902572095
runtime: 0.0002556581497192383 s
numpy function: 288.6749902572095
runtime: 4.681897163391113e-05 s
